name: Bug Report
description: "Report Chrome++ Bug"
title: "[Bug] "
body:
  - type: checkboxes
    id: ensure
    attributes:
      label: Verify steps
      description: Before submitting, please check the following applicable options to prove that you have read and understood the following requirements, otherwise the issue will be closed.
      options:
        - label: I have carefully read the [INI configuration file](https://github.com/Bush2021/chrome_plus/blob/main/src/chrome%2B%2B.ini) and understand the function of each configuration item.
          required: true
        - label: I have not searched for the problem I want to raise in the [Issue Tracker](https://github.com/Bush2021/chrome_plus/issues).
          required: false
        - label: I have provided the simplest configuration that can be used to reproduce the error I reported.
          required: true
        - label: I make sure to describe the problem in English.
          required: true

  - type: textarea
    attributes:
      label: Version Information
      description: Please provide a screenshot of `chrome://version/`.
    validations:
      required: true
  - type: textarea
    attributes:
      render: yaml
      label: Configuration File
      description: Please paste the simplest `chrome++.ini` content used to reproduce the problem.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Please provide a detailed description of the error and the steps to reproduce the error.
    validations:
      required: true
